<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_SelectedRoles_AssociatedLocations</name>
   <tag></tag>
   <elementGuidId>51da40f4-3e2a-4c78-9d48-f8cf6fe222e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;relative&quot;]/button[contains(@id,&quot;headlessui-listbox-button&quot;)]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
